AWSTemplateFormatVersion: '2010-09-09'
Description: Ride Planning Feature
Parameters:
  APIStageName:
    Description: Stage name to deploy the API to
    Type: String
    Default: dev
    AllowedPattern: '[A-Za-z0-9]*'
    MinLength: '1'
    MaxLength: '64'
    ConstraintDescription: must contain only alphanumeric characters (1-64 chars)
  DynamoReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '10000'
    ConstraintDescription: must be between 1 and 10000
  DynamoWriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '10000'
    ConstraintDescription: must be between 1 and 10000
Resources:
  RidePlanningDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tbl_ride_planning
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: ride_planning_id
        AttributeType: S
      - AttributeName: ride_properties_hash
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: ride_planning_id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: time_to_live
        Enabled: true
      LocalSecondaryIndexes:
      - IndexName: ride_properties_hash
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: ride_properties_hash
          KeyType: RANGE
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
          - ride_planning_id
  RidePlanningApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Ride Planning Feature
      EndpointConfiguration:
        Types:
        - REGIONAL
      Name: RootRidePlanningApi
  RidePlanningApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
        - RidePlanningApiGateway
        - RootResourceId
      PathPart: ride_planning
      RestApiId:
        Ref: RidePlanningApiGateway
  RequestRidePlanningApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestRidePlanningFunction.Arn}/invocations
      ResourceId:
        Ref: RidePlanningApiGatewayResource
      RestApiId:
        Ref: RidePlanningApiGateway
  RequestRidePlanningApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - RequestRidePlanningApiGatewayMethod
    Properties:
      RestApiId:
        Ref: RidePlanningApiGateway
      StageName: Dev
  RequestRidePlanningFunctionIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RequestRidePlanningLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - apigateway.amazonaws.com
            - sns.amazonaws.com
            - sqs.amazonaws.com
      Policies:
      - PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - lambda:Invoke
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - sns:GetTopicAttributes
            - sns:Publish
            - sns:Subscription
            Effect: Allow
            Resource: '*'
        PolicyName: RequestRidePlanningLambdaPolicies
  RequestRidePlanningFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: ride-planning-package-bucket-321321321
        S3Key: ride-planning/b9021803517031933b532ef57cc2d46f
      FunctionName: request_ride_planning
      Handler: main.handler
      MemorySize: '128'
      Role:
        Fn::GetAtt:
        - RequestRidePlanningFunctionIAMRole
        - Arn
      Runtime: python3.12
      Timeout: '10'
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: tbl_ride_planning
          SNS_TOPIC_ARN:
            Ref: RidePlanningNotificationTopic
          POWERTOOLS_SERVICE_NAME: request_ride_planning
          POWERTOOLS_LOG_LEVEL: INFO
  RequestRidePlanningFunctionApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - RequestRidePlanningFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: arn:aws:execute-api:sa-east-1:975050191502:q14j8ra0e4/*/POST/ride_planning
  RidePlanningNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: RidePlanningNotificationTopic
      TracingConfig: Active
  RidePlanningProcessRequestQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RidePlanningProcessRequestQueueDLQ
  RidePlanningProcessRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RidePlanningProcessRequestQueue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - RidePlanningProcessRequestQueueDLQ
          - Arn
        maxReceiveCount: 3
  RidePlanningProcessRequestQueueNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint:
        Fn::GetAtt:
        - RidePlanningProcessRequestQueue
        - Arn
      TopicArn:
        Ref: RidePlanningNotificationTopic
      FilterPolicy:
        ride_planning:
        - REQUEST_RIDE_PLANNING
  RidePlanningProcessRequestQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: RidePlanningProcessRequestQueue
      PolicyDocument:
        Statement:
        - Action:
          - SQS:SendMessage
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - RidePlanningProcessRequestQueue
            - Arn
          Principal:
            AWS: '*'
          Sid: topic-subscription-arn-RidePlanningProcessRequestQueueNotificationSubscription
